### ISSUE TITLE
<Question!> 

### ISSUE THREAD

**Issue by LunaThePotato** [aqariio/Fowl-Play#1]
Hello!
I would like to ask if you have a link where i can donate/tip (something like Ko-fi) u for creating this mod? c:
I very much love the implementation of the Rock Pigeons and the other birds so far in this mod and wish to show my support for u if possible! Thank you for your time!

**Comment by aqariio** [comment]
Thank you so much for the kind gesture! Unfortunately, I do not have anything set up for donations, and personally, I make mods as a hobby. I don't really expect to receive anything in return. Plus, the fact that there are people who enjoy my mod is support enough! :)

**Comment by LunaThePotato** [comment]
ahh damn okis ;w;
Then continue on the good work then m8!
I really hope there would be a possibility to befriend a pigeon too   in game too sometime in the future. But its ur mod & you do you okay! ^-^

**Comment by aqariio** [comment]
If you mean taming, you already can! Just feed the pigeon any food that you have to tame it. You can also give it bundles to deliver to other players. The wiki should contain a bit more information, although it's pretty empty at the moment.

**Comment by LunaThePotato** [comment]
oo okis, i have em tamed uwu
just wondering if there's a way for me to just have em loaf n not follow me into dangerous areas ;w; (Unless there is already and im just being dum ;;;;w; [Likely whats happening]) as right clicking isnt working like i would think it does for the puppers, cats & Parrots

**Comment by aqariio** [comment]
Oh, I forgot that I didn't add the right click function for them to sit. I'll add that in the next update.

**Comment by LunaThePotato** [comment]
o shizzles thanks m8! ;w;;; ❤️

**Comment by LunaThePotato** [comment]
i feel bad for msg a lot (_at least i feel like i am_ 😓) but seems i found a bug with the pigeons, as they don't stay loafed all the time.
They'll either get up on their own after a while and start hovering in the air for a bit then teleport to me regardless of distance.
