### ISSUE TITLE
[Feature Request] Sort bird spawn eggs alphabetically

### ISSUE THREAD

**Issue by Disketaa** [aqariio/Fowl-Play#11]
Every Minecraft spawn egg sorted by an alphabet. So it may be a nice touch to stay consistent with vanilla.

**Comment by aqariio** [comment]
The mod's spawn eggs are sorted alphabetically, but they aren't mixed in with the vanilla spawn eggs, instead being placed at the very end. This is done on purpose to separate the mod's spawn eggs from the ones in the base game.
