### ISSUE TITLE
configurability, and mobs not showing up on xaeros minimap

### ISSUE THREAD

**Issue by toastedfoxx** [aqariio/Fowl-Play#14]
i was wondering if you could make this mod more.. configurable, like spawn weight, sound volume, and the ability for seagulls to take your food right out of your hand if possible, i was gonna ask on discord, but i dont know if there is a server for this, so i'll just have to come here

**Comment by aqariio** [comment]
Spawning configuration is planned for the next update. I don't think I'll add the ability for gulls to take food out of inventories, as I want to stick with vanilla interactions. Sound volume is not planned, but you can simply install a mod that lets you customize individual sounds, like https://modrinth.com/mod/sound-controller

As for Xaero's Minimap, I have never used it before, so it might take me a while to find the issue. The mod is also closed source, which means that it will be difficult to find or fix potential incompatibilities.

**Comment by aqariio** [comment]
![image](https://github.com/user-attachments/assets/ec646ed9-d9f7-48ae-839c-a76ddf90d645)
The mobs seem to show up on the minimap just fine. However, the entity radar does have a vertical range. If the birds are flying far above you or in a tree, they might not appear. (the raven is part of the next update)
