### ISSUE TITLE
Will the mod be on Forge?

### ISSUE THREAD

**Issue by santacapra** [aqariio/Fowl-Play#15]
Ik fabric is good for performance and a lot of things, just curious since i'm working on a modpack for Forge :p

**Comment by aqariio** [comment]
I currently have a special version on GitHub that is compatible with Sinytra Connector. I _might_ make a Forge port in the future, but it's not really a priority right now, unfortunately.

**Comment by dsniav** [comment]
Hey guys, there's actually now a hotfix mod for the swimming issue on the connector. It resolves the issue completely (including for newly spawned mobs) without any need for the command. Here it is: https://github.com/unilock/sinytra1343/releases/tag/1.1.0

**Comment by santacapra** [comment]
Nice!!!
