### ISSUE TITLE
New Pigeon Bug!

### ISSUE THREAD

**Issue by LunaThePotato** [aqariio/Fowl-Play#16]
_Guess who's back?... Back again_ 'w'

hiya just letting you know that I've come across a new bug with the pigeons i think i just spotted. While they do stay loafed as they should like parrots n other pets that sit, it seems they still teleport to you and unloaf themselves when I load back the chunk they're loafing in(?)
Just FYI, the world I'm in is a smol island in the middle of a giant ocean biome so i didn't really come across this issue before till i went out my way to explore beyond the seas and came back to see the pigeons have blipped themselves to me at the edge of the island. They even somehow followed me thru a nether portal that was hundreds of blocks from my main island chunk where they're originally loafed in 😰 

I hope my story can help too ;w;
And thank you for your time too once more! 😅

**Comment by aqariio** [comment]
Huh, I guess the pigeons don't save whether they're sitting or not when they get unloaded? I'll include the fix in the next update, but it might take a while.

**Comment by aqariio** [comment]
I did some testing, and I don't seem to notice this problem? Either I've changed something since then that coincidentally fixed this issue, or something else is at play here. I guess it should be fixed now.

**Comment by LunaThePotato** [comment]
ooooohh so there was something off about them? :o
okis ill keep the pigeons bounded by leads like i did before when they unloaf themselves. it oddly works ;w;
