### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by shinycolororange** [aqariio/Fowl-Play#2]
Hey, I just wanted to say that I really enjoy this mod! I've always thought Minecraft lacked birds, so it's great to see this addition.

Since the mod is still in alpha, I wanted to offer some feedback. Sometimes, when walking near a forest, the bird sounds can get too loud too quickly, and they don't stop until you completely leave the area. This becomes especially noticeable if you have ambient sounds installed, as it makes the issue worse.

I'm not sure how to fix it, but if it's possible to mute specific birds that are extra loud via a config option, that could help without needing to change the mod itself. Otherwise, I'm not sure how to address this issue without changing the spawn rates.

**Comment by aqariio** [comment]
Hi, thanks for the feedback! I really appreciate it.

Would you mind sending a video (with audio) of the bird sounds? I usually play with 30% master volume, which might make the birds quieter than they actually are, and I haven't balanced their volumes with other mobs yet. The video could give me an idea of how loud they might be.

**Comment by shinycolororange** [comment]
Sure!

After recording and testing, I can provide more precise feedback. I noticed that when using only the ambient mod, the bird sounds are more consistent and not as "harsh." However, I found the "blue jay calls" sound particularly harsh on the ears, and sometimes the bird sounds play too frequently and too quickly.

I recorded the same forest with only the ambient mod sounds, your mod sounds, and both combined. Here are the video links!
https://www.youtube.com/watch?v=4KxQf1_CB1A
https://www.youtube.com/watch?v=VEb3wDOUaGA
https://www.youtube.com/watch?v=CVZ4TK0_Q_s

**Comment by aqariio** [comment]
Thank you so much for your help!

I'm not exactly sure why the bird sounds in my mod are inconsistently played. It might be a result of how Minecraft's random system works, but I've noticed that there are periods where no birds make noise, and periods where every single bird starts making noise at the same time. 

I've reduced the volumes of blue jay and cardinal calls, reduced the frequency of them playing, and added a few more variations so they're less repetitive. Hopefully in the near future I can fix the above issue of them all calling at the same time. I'll upload the new version soon.

As for the calls being harsh, I'm not too sure how I could make them more pleasing. I suppose I can add more birds with more consistent calls, like sparrows. If you have any suggestions that would be great!

**Comment by shinycolororange** [comment]
Thanks, it's better now! 
It might also be subjective what people find too loud or annoying when it comes to sounds. I'm just happy to have more birds in Minecraft! Maybe in a future update, you could add an option to adjust or mute certain birds, so users can customize it to their liking.

**Comment by aqariio** [comment]
I will definitely consider that! Thanks again for the help!
