### ISSUE TITLE
Baby Penguins using wrong model? 1.21.1

### ISSUE THREAD

**Issue by guytoothpick** [aqariio/Fowl-Play#3]
I wanted to see the penguin baby
and...
![2024-10-26_22 21 55](https://github.com/user-attachments/assets/121c0823-c6e0-4880-a796-e0a9dad04ac9)

**Comment by aqariio** [comment]
Yeah... the penguins are pretty buggy right now, and baby penguins don't have a proper model yet. I'll fix this in the next update.
