### ISSUE TITLE
Birds chirp when loading into a chunk

### ISSUE THREAD

**Issue by MrXBlade** [aqariio/Fowl-Play#4]
Probably a niche issue for most people but when birds get loaded in, they chirp.

When using a mod like Waystones, teleporting into a forest will cause you to be barraged by bird songs for the first seconds
With that, I read the closed issues and I feel like the bird sounds are still too loud compared to other things? Not sure what's going on.

Loving the vibe this mod gives though :)

**Comment by aqariio** [comment]
I'm glad you enjoy the mod!

I've further reduced the volumes of all the bird calls, and hopefully this time they are finally close to the volume of vanilla mob sounds. I've also fixed the issue of birds almost always making sounds when first loaded.
