### ISSUE TITLE
About the mod...

### ISSUE THREAD

**Issue by santacapra** [aqariio/Fowl-Play#5]
I just found this mod and wow, it looks awesome :D I love birds so i really wanted to install it, but since my modpack is for 1.20.1 and updating it to 1.21 isn't feasible for me, I decided against getting it..

I hope sometime in the future you'll considering making a 1.20.1 version with the new features. Also, I think the reason this mod hasn't taken off has something to do with it mainly being 1.21, since that is generally a trend i've observed with mods. This mod is really interesting and it definitely deserves way more attention than it currently has lol, There aren't a lot of mods that add birds to Minecraft so I absolutely support the development and look forward to seeing where it goes!! :]

(I also have a bunch of ideas for this mod, i'm kind of an idea generator and super into birds, so let me know if you're interested in hearing them :P)

Good luck with the mod development! ^^

**Comment by aqariio** [comment]
Hello! First off, I really appreciate you taking the time to comment, and I'm glad you found my mod interesting! I originally updated this mod to 1.21 to get myself motivated to continue the mod, so hopefully there aren't too many things that need changing and I can get a 1.20.1 version out soon (probably within a week or two, if I'm not busy).

As for your ideas, I am definitely interested in hearing them. If you could leave them in this issue, that would be great!

**Comment by santacapra** [comment]
Ok here comes a ton of text!

[Savannah] Secretarybird (Hunts snakes)
[Savannah] Snake (to be hunted :D )
[Savannah] Blackbird Flocks
[Savannah] Harpy Eagle

[Arctic Biomes] Gyrfalcon
[Snowy Tundra] Ptarmigan (These guys are basically arctic pigeons, They have brown coats in the summer and white in the winter, adding integration with Serene Seasons could be quite interesting!)
[Global, more common in elevated areas) Peregrine Falcon
[Plains] Pigeon
[Plains, Forest, Taiga] Crow
[Forest, Taiga, Snowy Taiga] Raven
[Global, more common in Mountains] Peregrine Falcon
[Global, rare, more common within 1000blocks of Ocean biomes] Osprey
[Jungle] Toucan
[Jungle] Sicklebills (Brown/Black/Black-billed/Pale-billed, these all have really cool calls)
[Savannah] Secretarybird (Hunts snakes)
[Savannah] Snake (to be hunted :D )
[Savannah] Blackbird Flocks
[Savannah] Harpy Eagle

Also, I wrote literally twice the amount of text than what's here, I just haven't posted it all because I don't want to overwhelm you. A lot of it is also pretty ambitious. But let me know if you want to see that too! (warning: it is a wall of text xD)

Enjoy! :)

**Comment by aqariio** [comment]
Okay, that is quite a bit! 

My current focus is on the ambiance side, adding birds with simpler behaviours whose primary purpose is to make noise. Once I'm done with sparrows, finches and chickadees, I'll start moving on to more unique birds. I plan on adding only one or two birds from each family, though that can change.

Peregrine falcons, ospreys and eagles are all on my list of things to add, although my list has grown quite long and I'm not sure if I can follow through. New world Blackbirds are going to be added as well, although I'm not sure if you were referring to old world blackbirds. I also plan on adding flocking behaviours in the future, likely together with smaller birds like sparrows or geese and ducks. 

I'm not sure if I want to add any non-bird mobs, as I want this mod to only focus on birds. Although, I have no problem with adding integration with another mod that adds them. 

I also definitely need to add more birds to some other biomes. I've been thinking about adding some birds that lost the mob vote, like ostriches and vultures (which are planned). 

Thank you so much for your suggestions! I will definitely take some time to think about the birds I want to add! Also, please do post the rest of your ideas! Even if I can't add all of them, there will definitely be some features that I can fit into the mod!

**Comment by santacapra** [comment]
I was referring to old world blackbirds, like you know those _swarms_ of birds in the Savannahs of Africa? That kind :]

And my other ideas mainly involve complex bird behaviors, and potentially custom armor and wings that the player can wear :p

**Comment by aqariio** [comment]
> I was referring to old world blackbirds, like you know those swarms of birds in the Savannahs of Africa?
Ah, I see. I'm afraid I'm not too familiar with old world birds at this moment, I'll have to do some research.

I plan on adding boids simulation for only smaller birds, while geese and ducks fly in v-formation. I'll have to see what the performance impact is.
Another behaviour I have planned is nesting, but that might take a bit of work.
I will consider custom equipment, although I want to focus on the animals for now.

Thanks for the suggestions!

**Comment by santacapra** [comment]
of course ^^ good luck!
